### ISSUE TITLE
[Feature Request] Allow for nested folder / zip file of plugin

### ISSUE THREAD

**Issue by contentsync** [sketchpacks/bug-reports#10]
### Steps to reproduce
Have a sketch plugin repository with the skechtplugin as a subfolder or zip file within the repo. 

### Current behavior
Download on sketchpack gets whole repo and not the subfolder / subfile.

### Expected behavior
Would be nice to add an item on the root path or somewhere to specify where to file the folder or file: other /myfolder/myplugin.sketchplugin or /myfolder/myplugin.zip.

### Workaround
Not know? Any help would be great. Do not want to create a second repo.

**Comment by adamkirkwood** [comment]
Fixed in https://github.com/contentsync/SketchContentSync.sketchplugin/issues/31
