### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by bensmeets** [sketchpacks/bug-reports#13]
Installed the app, started it, bounces 2 times in the dock and disappears without doing anything at all.

**Comment by adamkirkwood** [comment]
@bensmeets What happens when you click on the diamond icon in the menu bar?

![sketchpacks-snapshot](https://cloud.githubusercontent.com/assets/52746/24428963/00082ebc-13c5-11e7-9c76-934e068bc453.jpg)

**Comment by bensmeets** [comment]
Works! Cool. Must have not seen that the first time. Cheers!

**Comment by adamkirkwood** [comment]
@bensmeets Awesome. Glad to hear it.
