### ISSUE TITLE
Sketchpacks open a terminal automatically in v0.5.3!

### ISSUE THREAD

**Issue by josealvarezn** [sketchpacks/bug-reports#14]
**Platform: **
**Sketchpacks for macOS Version: **

### Steps to reproduce
When you activate the "Launch at startup", in the next restart... Sketchpacks open the terminal window.

### Current behavior
<img width="602" alt="screen shot 2017-04-01 at 8 27 33 am" src="https://cloud.githubusercontent.com/assets/16816916/24578767/81c6ec16-16b5-11e7-8dc1-e107d269856e.png">

### Expected behavior
Don't open the terminal without my permission.

**Comment by josealvarezn** [comment]
When I try close the terminal's windows, Sketchpacks is closes too! 😞
![image](https://cloud.githubusercontent.com/assets/16816916/24578778/dd4d6d44-16b5-11e7-8a37-d8a788810df6.png)

**Comment by adamkirkwood** [comment]
@josealvarezn Hey Jose. `v0.5.4` was just deployed to address this issue.

What it will do is remove your faulty old Login Item for Sketchpacks. All you have to do is re-enable `Launch at startup` to re-add the fixed Login Item.

Please confirm the fix and I'll close this issue out.

Thanks again for the bug reports! We appreciate them a lot!

**Comment by demersdesigns** [comment]
@adamkirkwood I installed v0.54 and with `Launch at startup` selected, I didn't have this issue. It appears to be fixed. 👍
