### ISSUE TITLE
Pasting into search box doesn't work

### ISSUE THREAD

**Issue by marklamb** [sketchpacks/bug-reports#16]
**System details:**
Darwin Marks-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

**Platform:** macOS Sierra
**Version:** 0.5.4

- Open Sketchpacks

- Try to paste clipboard

- Nothing happens — both command + v or right click menu do not appear.

Love the potential of the plugin as I already [tweeted](https://twitter.com/marklamb/status/847620849704108032), but it needs some help which I'd be glad to assist with. Couple of suggestions would be to more clearly split the "My Library" and "Browse" sections, as the search does not currently work in "Browse" and seems broken.

**Comment by davo** [comment]
+1

Can confirm this behaviour, also the search box field does not support / responde with other traditional shortcuts:

- ⌘ + A to select all characters within the search box
- ⌘ + X to cut characters based on selection

Also, the search box field does not support contextual menus.

**Comment by marklamb** [comment]
Yeah it's almost unusable TBH.

**Comment by adamkirkwood** [comment]
@marklamb @davo `v0.5.6` was released and addresses this issue.

I'm closing this issue out, but have created another issue to track the other piece of feedback.

This way we can keep laser focus on individual bugs/issues.
