### ISSUE TITLE
MacOS Sierra - Sketchpacks crash on load

### ISSUE THREAD

**Issue by zmilley** [sketchpacks/bug-reports#2]
When i start the app it crashes and disappears from the dock. However in activity monitor the app i running and the helper is to.

**Comment by Barizpwnz** [comment]
When I start the app, nothing happens, not in process not in Doc

**Comment by adamkirkwood** [comment]
@zmilley @Barizpwnz Sorry this bug is blocking you guys from trying it out.

Would you mind copy and pasting the contents of `~/Library/Logs/Sketchpacks/log.log` and pasting it into this issue?

**Comment by equinusocio** [comment]
@adamkirkwood  Same here, crash on start with this message:
<img width="532" alt="screen shot 2017-03-16 at 09 13 40" src="https://cloud.githubusercontent.com/assets/10454741/23987252/f50c0916-0a28-11e7-86cf-a4d99d344d99.png">

**Comment by Barizpwnz** [comment]
@adamkirkwood sorry, my bad, I haven't seen that software is running and icon appeared in tray :)))

**Comment by adamkirkwood** [comment]
@equinusocio v0.4.1 was just released. Please let me know if this issue has been resolved for you.

**Comment by equinusocio** [comment]
it's gone!

**Comment by adamkirkwood** [comment]
@zmilley I'm curious, have you checked your desktop's status/menu bar? The app does not run like a standard app, but rather lives as a menu bar accessible application.

You can access Sketchpacks from the diamond. But if you have already tried this, then my apologies. I'll continue to dig deeper for the problem and solution. Thanks for your patience.

![](https://pbs.twimg.com/media/C7EgU41VwAAGIIT.jpg)
