### ISSUE TITLE
New install doesn't recognize currently installed plugins.

### ISSUE THREAD

**Issue by zacharyprice** [sketchpacks/bug-reports#22]
**Platform:
Darwin zachary.xpressdocs.com 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017
**
**Sketchpacks for macOS Version:
root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
**

### Steps to reproduce
Install Sketchpacks, click menu icon, click "Installed"

### Current behavior
Sketchpacks doesn't recognize currently installed plugins.

### Expected behavior
To view a list of all plugins currently installed.

### Workaround
N/A

N/A

**Comment by adamkirkwood** [comment]
@zacharyprice This issue has been address and fixed in `0.5.7`.

Thanks for the report!

**Comment by zacharyprice** [comment]
@adamkirkwood Thank you bet much!

**Comment by zacharyprice** [comment]
*very (stupid autocorrect)
