### ISSUE TITLE
Makes Anima auto-layout plugin not work correctly

### ISSUE THREAD

**Issue by mattaningram** [sketchpacks/bug-reports#26]
**Platform: macOS**
**Sketchpacks for macOS Version: 0.5.6**

### Steps to reproduce
Install the Anima Auto-Layout (now called Launchpad) plugin, open Sketch file.

### Current behavior
Plugin is installed as a folder instead of just plugin file (which is what happens when you install manually) and plugin is buggy and displays wrong.

### Expected behavior
Plugin to function correctly in Sketch app as it does when manually installed directly from website.

### Workaround
Manually install plugin

**Comment by adamkirkwood** [comment]
Sketchpacks does not modify plugins.

Unfortunately the developers released a buggy version. Please reach out to the developers to fix plugin related bugs.
