### ISSUE TITLE
Search does not work in Installed tab

### ISSUE THREAD

**Issue by fbasara-loft48** [sketchpacks/bug-reports#27]
**Platform: macOS 10.12.4**
**Sketchpacks for macOS Version: 0.5.6**

### Steps to reproduce
- Open Sketchpacks
- Go to `Installed` 
- Type in keyword into search
- Hit Enter

### Current behavior

Search does not trigger, nothing happens

### Expected behavior

Search would filter out plugins that match keyword 

### Workaround

None

**Comment by adamkirkwood** [comment]
@fbasara-loft48 This issue has been fixed in `0.5.7`.

Thanks for the report!
