### ISSUE TITLE
[API] Rollup numbers for downloads and uploads are always the same across week, month, and all time

### ISSUE THREAD

**Issue by mludowise** [sketchpacks/bug-reports#31]
**Platform:** API
**API Version:** v1

### Steps to reproduce
Go to https://api.sketchpacks.com/v1/plugins/

### Current behavior
The numbers under each rollup for downloads and uploads are always the same. For example, `zeplin-sketch-plugin` says it has 20 downloads for `this_week`, `this_month`, and `all_time` which seems highly unlikely. 

```
"rollup": {
  "downloads": {
    "all_time": 20,
    "this_week": 20,
    "this_month": 20
  },
  "updates": {
    "all_time": 11,
    "this_week": 11,
    "this_month": 11
  }
},
```

### Expected behavior
The numbers would be different.

### Workaround
None.

**Comment by adamkirkwood** [comment]
@mludowise Given that we've only started officially tracking download and update metrics since June 8, we can't provide more data than that.

The counts will eventually eventually sort themselves out as time goes on.

**Comment by mludowise** [comment]
Thanks for the explanation. That makes sense.
