### ISSUE TITLE
Default to Full Lock is maybe too strong

### ISSUE THREAD

**Issue by iconmaster** [sketchpacks/bug-reports#39]
**Platform**
Darwin Beast-Machine.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Sketchpacks for macOS Version:**
Version 0.5.7

### Steps to reproduce

Install any plugin available in Sketchpacks.
Observe its "lock" status in the Managed view

![image](https://user-images.githubusercontent.com/935/28388730-4673c7f8-6c99-11e7-8477-fbb8159d4115.png)

### Current behavior

Sketchpacks seems to default all new plugins to the Full Locked state. This means the plugin will stay at exactly that version and no updates will be applied. 

### Expected behavior

While major plugin updates could result in broken workflows, I think the argument could be made for defaulting to a lesser lock. There are four available levels: I'd suggest defaulting at least to Patch Updates.

### Workaround

The user can of course change the lock state for every managed plugin. It's just a little tedious.

**Comment by adamkirkwood** [comment]
@iconmaster @mwhite05 With Sketchpacks 0.6.0, you now have the ability to define a default locking and updating strategy from the `Preferences` menu.

![screen shot 2017-09-09 at 5 41 49 pm](https://user-images.githubusercontent.com/52746/30245173-2e46621a-9586-11e7-9aa6-755968060420.png)
