### ISSUE TITLE
Blank application window | 10.11.6

### ISSUE THREAD

**Issue by j0sc** [sketchpacks/bug-reports#42]
**Platform: ** 10.11.6
**Sketchpacks for macOS Version: ** 0.6

### Workaround

Please don't tell me that a plugin organizer is 10.12+ only. Really, guys?

**Comment by josealvarezn** [comment]
Same here! 😔
<img width="1440" alt="screen shot 2017-09-06 at 6 31 13 pm" src="https://user-images.githubusercontent.com/16816916/30137571-ed19515e-9331-11e7-94e1-b0f39c56ba33.png">

**Comment by gamecubate** [comment]
Ditto.

**Comment by patrickhansen** [comment]
same issue here on OS X 10.12.6 - Sketch 46.2

**Comment by hami-studio** [comment]
same. MacOS 10.12.6 | SketchApp 46.2

**Comment by TheBreznsoiza** [comment]
blank window. MacOS 10.12.6 | SketchApp 46.2

**Comment by maxkonovalov** [comment]
Same here, MacOS 10.12.6, Sketch 46.2

**Comment by mijlee** [comment]
Same here MacOS 10.12.6 and Sketch 46.2

https://www.dropbox.com/s/c589mv7jzrevbgr/Screenshot%202017-09-07%2015.49.31.png?dl=0

**Comment by jschelling** [comment]
Same. MacOS 10.12.6 and Sketch 46.2

**Comment by patrikkernke** [comment]
Same. MacOS 10.12.6 and Sketch 46.2

**Comment by adamkirkwood** [comment]
@gamecubate @patrickhansen @hami-studio @DasBlatz @maxkonovalov @mijlee @jschelling @patrikkernke We've rolled out the fix in v0.6.1 and is available for download at http://bit.ly/GetSketchpacks

Please let us know if this issue persists

**Comment by adamkirkwood** [comment]
@j0sc Sorry for the inconvenience. 

As a two-person team, we're doing our best to do regression testing on as many macOS versions as possible.

v0.6.1 should fix this issue and is [available for download](http://bit.ly/GetSketchpacks)

**Comment by hami-studio** [comment]
@adamkirkwood Thank you so much for the update. Working now. Really love what you guys are doing :)

**Comment by adamkirkwood** [comment]
I'm closing this issue as it has been resolved in v0.6.0
