### ISSUE TITLE
Bug: Command+comma stops working in other apps when Sketchpacks is open

### ISSUE THREAD

**Issue by chibicode** [sketchpacks/bug-reports#43]
### It seems that sketchpacks is stealing keyboard event for command+comma from other apps.

**Platform:** Darwin Shus-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64

**Sketchpacks for macOS Version:** 0.6.1

### Steps to reproduce

1. Close sketchpacks
2. Open any app (like Google Chrome) and hit command+comma keyboard shortcut to open a preferences tab
3. Open sketchpacks
4. Go back to Google Chrome and hit command+comma again

### Current behavior

Google Chrome doesn't recognize command+comma

### Expected behavior

Google Chrome recognizes command+comma and opens its preferences window

### Workaround

Change "Preferences..." to some other keyboard shortcut for all apps

<img width="461" alt="screen shot 2017-09-12 at 9 45 26 am" src="https://user-images.githubusercontent.com/992008/30311684-28d0e47a-979f-11e7-924f-fb03fe655187.png">

**Comment by josealvarezn** [comment]
Same here!

**Comment by ggamel** [comment]
Confirmed. Reproducible on my end, too. Was driving me crazy until I randomly happened to try closing Sketchpacks. Only solution is to keep Sketchpacks closed until an update is released to resolve this bug.

**Comment by adamkirkwood** [comment]
@chibicode @josealvarezn @ggamel We just released `v0.6.2` which resolves this issue.

Thanks for reporting this annoying bug!
