### ISSUE TITLE
Failed to install Loose!

### ISSUE THREAD

**Issue by teeerevor** [sketchpacks/bug-reports#48]
**Platform: **
Darwin TPro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Sketchpacks for macOS Version: **
 v0.6.2

### Steps to reproduce
- Search for "loose"
- Click "Install" button

### Current behavior
Notification: Failed to install Loose!

### Expected behavior
Notification: Installed Loose!

### Workaround
Download and install manually.

I noticed the Download button on the sketchpacks site is also failing.
(https://sketchpacks.com/teeerevor/loose-sketch-plugin)

The download button returns this link (I'm keen to remove the !)
https://api.sketchpacks.com/v1/plugins/com.teeerevor.sketch.loose!/download

I've also shipped two releases to github yet none are showing up or your site.

**Comment by willdavis** [comment]
Hi @teeerevor it looks like the `!` in your plugin identifier is causing the problem.

Removing the `!` would be the quickest fix.  Right now only alpha-numeric and `- _ .` characters are accepted in the URL params.

I need to add a validation to make sure this is caught before it gets to that part, so thanks for the feedback!  I'm also open to extending the whitelist for more characters.  Just need to make sure they stay URL-Safe.

also, we are working on a dashboard so issues like this will be easier to see in the future.  It should be ready soon-ish.

**Comment by willdavis** [comment]
It looks like there may be a problem with your `1.0.2` release.  I tried installing it in sketchpacks and it was able to install, however, it went to the un-managed tab.

I opened up the release assets and noticed that the `manifest.json` still contains:
```json
{
  "identifier": "com.teeerevor.sketch.loose!",
  "version": "1.0",
}
```

Although, it looks like the registry caught your latests changes to the identifier:
https://api.sketchpacks.com/v1/plugins/com.teeerevor.sketch.loose

**Comment by teeerevor** [comment]
@willdavis thank you.
