### ISSUE TITLE
Update not picking up newest version

### ISSUE THREAD

**Issue by oskarkrawczyk** [sketchpacks/bug-reports#6]
I was just testing the app, while I love the idea, seems like it's a bit unreliable at this time.

See how Sketchpacks is reporting `0.2.0` is the newest version, while `0.2.3` actually is:

<img width="1244" alt="screen shot 2017-03-17 at 07 24 51" src="https://cloud.githubusercontent.com/assets/34213/24031494/460e3752-0ae3-11e7-992a-39488d12ad15.png">

**Comment by adamkirkwood** [comment]
@oskarkrawczyk Hi Oskar,

We are aware of this issue as we've noticed quite a few plugins in this situation.

Our registry is quite strict when it comes to indexing plugins, as are strictly parsing valid `manifest.json` files found within the plugin bundles to respect data integrity.

Unfortunately, Auto Layout's [manifest.json](https://github.com/AnimaApp/Auto-Layout/blob/master/AutoLayoutPlugin.sketchplugin/Contents/Sketch/manifest.json#L102) is reporting a parse error which prevents us from parsing their latest updates.

```
Error: Parse error on line 102:
...                   ],    },    "ident
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```

So the only real solution I know of at this point is that we will be reaching out to the various plugin owners with invalid `manifest.json` files to hopefully correct them.

Thanks for the feedback and continued support!

**Comment by adamkirkwood** [comment]
@oskarkrawczyk I'm closing this issue out as Auto-Layout is now integrated with Sketchpacks Relay.

![screen shot 2017-03-24 at 12 48 06 am](https://cloud.githubusercontent.com/assets/52746/24285058/94757f70-102b-11e7-8d91-d6bb680870e2.png)
