### ISSUE TITLE
Lots of missing plugins

### ISSUE THREAD

**Issue by RustyGoodman** [sketchpacks/bug-reports#8]
Would you prefer that users share plugins that are missing? Might be worth mentioning on your site.

For me…
https://github.com/truthlabs/sketch-unlock-all-layers
There's an alternate available but this one has the key command.

Also, Sketch Runner.
http://sketchrunner.com/

**Comment by adamkirkwood** [comment]
Hey @russgoodman,

It seems our registry has picked up [Unlock All Layers](https://sketchpacks.com/truthlabs/sketch-unlock-all-layers).

We'll reach out to Sketch Runner and see if we can get them integrated into the registry as well.

As for plugin submissions, we'll make that more obvious on our registry's website. We're trying to get Sketch Plugin Developers to leverage [Sketchpacks Relay](https://github.com/integration/sketchpacks-relay) to take advantage of auto-updating capabilities.

**Comment by RustyGoodman** [comment]
Ok very cool. This is actually a slightly different version of Unlock All Layers. This one has key commands built into it. Thanks for the great product.

**Comment by willdavis** [comment]
Going to close this issue, but wanted to add a little extra details.

We encourage developers to integrate with Sketchpacks Relay, but we are also data mining the sketchplugins directory for plugins. Integrating with Sketchpacks Relay will only add plugins that you are the owner of.

@russgoodman if you would like to add plugins that you do not own, you can add them to the [sketchplugins directory](https://github.com/sketchplugins/plugin-directory). (create a pull request to add the plugins).

We've made some improvements to our background jobs that upsert plugins so almost all of the plugins that are available in the sketchplugins directory are also available in Sketchpacks.

Here are the current stats for the background job:
```
341 plugin(s) detected
323 plugin(s) are present in Sketchpacks
7 plugin(s) had invalid attributes (blank identifiers)
1 plugin(s) had a duplicate identifier 
7 plugin(s) had a missing manifest.json 
3 plugin(s) had an invalid repository name on Github 
```
