### ISSUE TITLE
I can't open the file

### ISSUE THREAD

**Issue by leewilson78** [sketchpacks/bug-reports#9]
I'm on macOS Sierra (Version 10.12.3).

I just downloaded the app, double clicked from the Applications folder and nothing happens, I tried this on two macs, same problem.

**Comment by adamkirkwood** [comment]
@leewilson78 So when you click on the 💎 menu bar icon (diamond), the window doesn't load any content?

<img width="366" alt="screen shot 2017-03-16 at 2 35 39 pm" src="https://cloud.githubusercontent.com/assets/52746/24219897/aa458e0c-0f05-11e7-952c-3829b91b3136.png">

**Comment by leewilson78** [comment]
Ok stand down men, absolute newbie move here, I didn't notice that it added a menu bar icon... Apologies.

**Comment by adamkirkwood** [comment]
@leewilson78 No worries! We'll work on making this more obvious.

For now, I'll close this issue out.

As always, thanks for the feedback!
